version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price_tracker
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin1234
      DB_NAME: price_tracker
    depends_on:
      - db
    networks:
      - nest_network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: price_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - nest_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nest_network:
    driver: bridge

volumes:
  postgres_data:
